language: en
pipeline:
- name: SpacyNLP
  case_sensitive: False
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: SklearnIntentClassifier
policies:
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.50
  ambiguity_threshold: 0.05
  core_threshold: 0.40
  fallback_core_action_name: action_default_ask_affirmation
  fallback_nlu_action_name: action_default_ask_rephrase
  deny_suggestion_intent_name: out_of_scope
- name: AugmentedMemoizationPolicy
  max_history: 10
- name: TEDPolicy
  epochs: 50
  hidden_layers_sizes:
    dialogue:
    - 16
    - 8
    label:
    - 16
    - 8
  max_history: 10
  batch_size:
  - 4
  - 8
- name: MappingPolicy
